name: Checkin
main: com.github.Mr0Unknown.Checkin.Main
version: 1.5.1
commands:
  qiandao
permissions:
  Checkin.player:
    description: 玩家默认拥有一部分权限
    default: true
    children:
  Checkin.create:
  Checkin.add:
  Checkin.remove:
  Checkin.set:
  Checkin.get:
