name: Checkin
main: com.github.Mr0Unknown.Checkin.Main
version: 1.5.1
commands:
  qiandao:
permissions:
  Checkin.create:
    description: 创建礼包
    default: op
  Checkin.add:
    default: op
    description: 添加手中的物品到礼包
  Checkin.remove:
    description: 删除礼包
    default: op
  Checkin.set:
    description: 设置礼包权限和时间
    default: op
  Checkin.get:
    description: 领取礼包
    default: true
  Checkin.getothers:
    description: 领取未领取完的礼包的物品
    default: true
  Checkin.list:
    description: 查看礼包列表
    default: true
  Checkin.reload:
    description: 重载配置文件
    default: true